 # ----------------------------------------------------------------------------
#
# Package             : zm-openid-consumer-store
# Source Repo         : https://github.com/Zimbra/zm-openid-consumer-store
# Travis Job Link     : https://travis-ci.com/github/asellappen/zm-openid-consumer-store/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: java

arch:
    - amd64
    - ppc64le

dist: bionic

jdk:
  - openjdk8
  - openjdk11
